#ifndef _LCOM_VIDEOCARD_MACROS_H
#define _LCOM_VIDEOCARD_MACROS_H

#define DIRECT_MODE_24 0x115
#define INDEXED_MODE 0x105
#define MENU_HEIGHT 80
#define MENU_COLOR 0xFFFFFF
#define BUTTON_MENU_HEIGHT 60 
#define BUTTON_MENU_WIDTH  200
#define BUTTON_MENU_Y 10
#define EXIT_BUTTON_X 80
#define ADD_KEYBOARD_BUTTON_X 300
#define CHANGE_BACK_BUTTON_X 520
#define CHANGE_LETTER_BUTTON_X 740

#define HRES 1024
#define VRES 768

#endif
